server.port=8080
server.servlet.context-path=/

spring.datasource.url=jdbc:postgresql://localhost:5432/social_network
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.platform=postgres